version: '3.0'

services:
  app:
    build: crm-app/.
    container_name: crm_app
    ports:
      - 8080:80
    volumes:
      - .:/app
    restart: always

  api:
    build: crm-api/.
    container_name: crm_api
    ports:
      - 3001:3000
    volumes:
      - .:/usr/src/api
    command: bash -c "npm run build && npm run migrate -- --rebuild && npm start"
    depends_on:
      - mysql_db
    links:
      - mysql_db

  mysql_db:
    build: database/.
    container_name: mysql_crm
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    command: --character-set-server=utf8
    restart: always
    env_file: database/.env

volumes:
  db-data:
